// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp4bvn5DVYUf7fCkHcVQTPF_78k33f6yE',
    appId: '1:368441996486:web:95297fa000451bab4993c7',
    messagingSenderId: '368441996486',
    projectId: 'data-analysis-56bba',
    authDomain: 'data-analysis-56bba.firebaseapp.com',
    storageBucket: 'data-analysis-56bba.appspot.com',
    measurementId: 'G-P1V47TY4S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGrGsMdC3SgF7PeBffnj1u3VDvyeW_ys',
    appId: '1:368441996486:android:0c4494b6f662316b4993c7',
    messagingSenderId: '368441996486',
    projectId: 'data-analysis-56bba',
    storageBucket: 'data-analysis-56bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl-FnF_LqlZ00EPUUqtDE-wUanf79qjPA',
    appId: '1:368441996486:ios:1c24d518e085f0a44993c7',
    messagingSenderId: '368441996486',
    projectId: 'data-analysis-56bba',
    storageBucket: 'data-analysis-56bba.appspot.com',
    iosBundleId: 'com.deepakumar452005.alimniDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl-FnF_LqlZ00EPUUqtDE-wUanf79qjPA',
    appId: '1:368441996486:ios:1c24d518e085f0a44993c7',
    messagingSenderId: '368441996486',
    projectId: 'data-analysis-56bba',
    storageBucket: 'data-analysis-56bba.appspot.com',
    iosBundleId: 'com.deepakumar452005.alimniDb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp4bvn5DVYUf7fCkHcVQTPF_78k33f6yE',
    appId: '1:368441996486:web:cd60e9d427225b214993c7',
    messagingSenderId: '368441996486',
    projectId: 'data-analysis-56bba',
    authDomain: 'data-analysis-56bba.firebaseapp.com',
    storageBucket: 'data-analysis-56bba.appspot.com',
    measurementId: 'G-WHZX715WC0',
  );
}
